from enum import Enum


class GameErrorReasons(Enum):
    ALL_PLAYERS_ALREADY_JOINED = "ALL_PLAYERS_ALREADY_JOINED"
    POSITION_OFF_LIMITS = "POSITION_OFF_LIMITS"
    PLAYER_CAN_NOT_PLAY = "PLAYER_CAN_NOT_PLAY"
    POSITION_ALREADY_FILLED = "POSITION_ALREADY_FILLED"
    GAME_ALREADY_ENDED = "GAME_ALREADY_ENDED"


class GameStage(Enum):
    GAME_ABORTED = "GAME_ABORTED"
    WAITING_FOR_PLAYERS = "WAITING_FOR_PLAYERS"
    PLAYER_WON = "PLAYER_WON"
    DRAW = "DRAW"
    IN_PROGRESS = "IN_PROGRESS"
